services:
  web:
    init: true
    build: .
    # change if needed (adjusts the permission of the generated folder)
    user: 1000:1000
    ports:
      - "8000:8080"
    volumes:
      # sync ressources folder
      - ../ressources:/usr/src/app/ressources
      - ../logs:/usr/src/app/logs
    
    restart: always



