services:
  speech2text:
    init: true
    build: .
    # change if needed (adjusts the permission of the generated folder)
    # user: 1000:1000
    volumes:
      - ../output:/usr/src/output
      - ../ressources:/usr/src/ressources
      - ../cache:/usr/src/cache

